apiVersion: v1
kind: Namespace
metadata:
  name: jnotebook-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jnotebook-reader
  namespace: jnotebook-reader
  labels:
    app: jnotebook-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jnotebook-reader
  template:
    metadata:
      labels:
        app: jnotebook-reader
    spec:
      containers:
        - name: jnotebook-reader
          image: jnotebook_reader:latest
          ports:
            - containerPort: 9088
          resources:
            limits:
              memory: 512Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: "0.5"
          env:
            - name: JNOTEBOOK_READER_SERVER_PORT
              value: "9088"
            - name: JNOTEBOOK_READER_STORAGE_TYPE
              value: "{s3}"
            - name: JNOTEBOOK_READER_S3_ENDPOINT
              value: "{S3_ENDPOINT}"
            - name: AWS_ACCESS_KEY_ID
              value: '{S3_ACCESS_KEY}'
            - name: AWS_SECRET_ACCESS_KEY
              value: '{S3_SECRET_KEY}'
            - name: JNOTEBOOK_READER_S3_BUCKET_NAME
              value: '{S3_BUCKET_NAME}'
---
apiVersion: v1
kind: Service
metadata:
  name: jnotebook-reader-svc
  namespace: jnotebook-reader
spec:
  type: NodePort
  ports:
    - name: tcp-rule-jnotebook-reader
      port: 9088
      protocol: TCP
      targetPort: 9088
  selector:
    app: jnotebook-reader